#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-logical_unification
Version  : 0.4.4
Release  : 1
URL      : https://files.pythonhosted.org/packages/e4/33/be50ec4b1844a2a91e5a7bbad50591441c05a2f24c3039e1a73c247534b8/logical-unification-0.4.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/e4/33/be50ec4b1844a2a91e5a7bbad50591441c05a2f24c3039e1a73c247534b8/logical-unification-0.4.4.tar.gz
Summary  : Logical unification in Python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-logical_unification-license = %{version}-%{release}
Requires: pypi-logical_unification-python = %{version}-%{release}
Requires: pypi-logical_unification-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(multipledispatch)
BuildRequires : pypi(toolz)

%description
# Logical Unification
[![Build Status](https://travis-ci.org/pythological/unification.svg?branch=master)](https://travis-ci.org/pythological/unification) [![Coverage Status](https://coveralls.io/repos/github/pythological/unification/badge.svg?branch=master)](https://coveralls.io/github/pythological/unification?branch=master) [![PyPI](https://img.shields.io/pypi/v/logical-unification)](https://pypi.org/project/logical-unification/)

%package license
Summary: license components for the pypi-logical_unification package.
Group: Default

%description license
license components for the pypi-logical_unification package.


%package python
Summary: python components for the pypi-logical_unification package.
Group: Default
Requires: pypi-logical_unification-python3 = %{version}-%{release}

%description python
python components for the pypi-logical_unification package.


%package python3
Summary: python3 components for the pypi-logical_unification package.
Group: Default
Requires: python3-core
Provides: pypi(logical_unification)
Requires: pypi(multipledispatch)
Requires: pypi(toolz)

%description python3
python3 components for the pypi-logical_unification package.


%prep
%setup -q -n logical-unification-0.4.4
cd %{_builddir}/logical-unification-0.4.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1640113765
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-logical_unification
cp %{_builddir}/logical-unification-0.4.4/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-logical_unification/45b077e352c945bbc3dfcc8cfe8aaf4211f2185c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-logical_unification/45b077e352c945bbc3dfcc8cfe8aaf4211f2185c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
